### ISSUE TITLE
Bug: All payment types are being returned

### ISSUE THREAD

**Issue by stevebrownlee** [day-cohort-70/Bangazon-API-team-3#10]
When the client performs a GET request to the `/paymenttypes` resources, only the payment types added by the authenticated user should be returned.

Currently, all payment types in the system are being returned.

**Comment by oliverkennelly** [comment]
on client side the fetch call is for payment-types and not paymenttypes, so it does not work on client!!!

**Comment by oliverkennelly** [comment]
client updated with a pull request

**Comment by oliverkennelly** [comment]
whomp whomp do it on server side not client

django.... my mortal enemy.......
