### ISSUE TITLE
Bug: Cart does not show items

### ISSUE THREAD

**Issue by oliverkennelly** [day-cohort-70/Bangazon-API-team-3#44]

**Comment by oliverkennelly** [comment]
no items are shown in cart!! ill work on this later but here are some things i noticed:

in orders.js the fetchWithResponse argument is currently 'cårt', should be profile/cart

in detail.js, the property being accessed is products, not lineitems (currently can't work on this until the lineitems issue is fixed)

**Comment by carsonruscin** [comment]
This was resolved as part of Ticket #43
