### ISSUE TITLE
***UPDATE ERD, MODEL, VIEW*** - LIKES

### ISSUE THREAD

**Issue by novofeels** [day-cohort-70/Bangazon-API-team-3#48]
We need to update our ERD to accomodate for the feature of users "liking" products

This will involve first updating our ERD to include a through table "likes" between products and users.

in the backend side I would think we add a many to many to products maybe something like below

likes = models.ManyToManyField(User, through='Like', related_name='liked_products')

**Comment by hamid-kordi** [comment]
hello , 
make new model,
every product get many 'like' from differnet user
and defferent user liked many product ,
then need new mode : 

```
class Like(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ulike')
	product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='plike')
	def __str__(self):
		return f'{self.user} liked {self.product.slug}'
```

**Comment by novofeels** [comment]
Hello Hamid,

Thank you for your input, I would like to clarify that we are indeed planning to implement a `Like` model to facilitate the many-to-many relationship between users (customers) and products. This model will also include a `created_date` to track when each like was created. Here’s the planned implementation:

```python
from django.db import models
from .customer import Customer
from .product import Product

class Like(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("customer", "product")

class Product(models.Model):
    # Other fields...
    likes = models.ManyToManyField(User, through='Like', related_name='liked_products')
```

This approach leverages Django's ManyToManyField with a through model, which is a common and efficient way to handle such relationships. This ensures we can track additional information, such as the creation date of each like, within the join table.

Thank you again for your feedback!

Best regards,
novo

**Comment by hamid-kordi** [comment]
Thanks for the details
Good luck Novo🤝
